cookie_secret = ""

[discord]
token = ""
client_id = ""
client_secret = ""
redirect_uri = ""

[patreon]
client_id = ""
client_secret = ""
creator_access_token = ""
creator_refresh_token = ""
redirect_uri = ""
